"""
Add Metrics and Detailed Comparison to Notebook
"""
import json

# Load existing notebook
with open('carbon24-clustering-comparison-evaluation.ipynb', 'r', encoding='utf-8') as f:
    notebook = json.load(f)

# Add Metrics Evaluation
notebook["cells"].append({
    "cell_type": "markdown",
    "id": "metrics-title",
    "metadata": {},
    "source": [
        "## 🎯 4. Clustering Quality Metrics\n",
        "\n",
        "Đánh giá chất lượng clustering với 3 metrics chính:\n",
        "- **Silhouette Score** (↑ higher is better): Đo độ tách biệt giữa các clusters\n",
        "- **Davies-Bouldin Index** (↓ lower is better): Đo độ compact và separation\n",
        "- **Calinski-Harabasz Score** (↑ higher is better): Đo tỷ lệ variance giữa/trong clusters"
    ]
})

notebook["cells"].append({
    "cell_type": "code",
    "id": "calculate-metrics",
    "metadata": {},
    "execution_count": None,
    "outputs": [],
    "source": [
        "# Load feature data for metrics calculation\n",
        "print('📊 Loading feature data for metrics...')\n",
        "df_features = pd.read_csv('carbon24_feature_selected/carbon24_feature_selected_standard.csv')\n",
        "\n",
        "with open('carbon24_feature_selected/selected_features.json', 'r') as f:\n",
        "    feature_info = json.load(f)\n",
        "\n",
        "numeric_features = [f for f in feature_info['numeric_features'] if f != 'relative_energy' and f in df_features.columns]\n",
        "X = df_features[numeric_features].values\n",
        "\n",
        "print(f'✅ Loaded features: {X.shape}')\n",
        "print(f'   Features used: {len(numeric_features)}')"
    ]
})

notebook["cells"].append({
    "cell_type": "code",
    "id": "compute-metrics",
    "metadata": {},
    "execution_count": None,
    "outputs": [],
    "source": [
        "# Calculate metrics for each method\n",
        "print('\\n' + '=' * 80)\n",
        "print('🎯 CLUSTERING QUALITY METRICS')\n",
        "print('=' * 80)\n",
        "\n",
        "metrics_results = []\n",
        "\n",
        "for method, data in results.items():\n",
        "    print(f'\\n{method}:')\n",
        "    print('-' * 60)\n",
        "    \n",
        "    if 'cluster' not in data['data'].columns:\n",
        "        print('  ⚠️  No cluster labels found')\n",
        "        continue\n",
        "    \n",
        "    labels = data['data']['cluster'].values\n",
        "    \n",
        "    # Filter out noise points for HDBSCAN\n",
        "    if method == 'HDBSCAN' and -1 in labels:\n",
        "        mask = labels != -1\n",
        "        X_filtered = X[mask]\n",
        "        labels_filtered = labels[mask]\n",
        "        print(f'  Filtered out {(~mask).sum()} noise points')\n",
        "    else:\n",
        "        X_filtered = X\n",
        "        labels_filtered = labels\n",
        "    \n",
        "    # Check if we have enough clusters\n",
        "    n_clusters = len(np.unique(labels_filtered))\n",
        "    if n_clusters < 2:\n",
        "        print(f'  ⚠️  Only {n_clusters} cluster(s) found, skipping metrics')\n",
        "        continue\n",
        "    \n",
        "    try:\n",
        "        # Sample for faster computation if needed\n",
        "        if len(X_filtered) > 5000:\n",
        "            sample_idx = np.random.choice(len(X_filtered), 5000, replace=False)\n",
        "            X_sample = X_filtered[sample_idx]\n",
        "            labels_sample = labels_filtered[sample_idx]\n",
        "            print(f'  Using sample of 5000 points for metrics')\n",
        "        else:\n",
        "            X_sample = X_filtered\n",
        "            labels_sample = labels_filtered\n",
        "        \n",
        "        # Calculate metrics\n",
        "        silhouette = silhouette_score(X_sample, labels_sample)\n",
        "        davies_bouldin = davies_bouldin_score(X_filtered, labels_filtered)\n",
        "        calinski = calinski_harabasz_score(X_filtered, labels_filtered)\n",
        "        \n",
        "        print(f'  Silhouette Score:      {silhouette:.4f}')\n",
        "        print(f'  Davies-Bouldin Index:  {davies_bouldin:.4f}')\n",
        "        print(f'  Calinski-Harabasz:     {calinski:.2f}')\n",
        "        \n",
        "        metrics_results.append({\n",
        "            'Method': method,\n",
        "            'Silhouette': silhouette,\n",
        "            'Davies-Bouldin': davies_bouldin,\n",
        "            'Calinski-Harabasz': calinski,\n",
        "            'N_Clusters': n_clusters\n",
        "        })\n",
        "        \n",
        "    except Exception as e:\n",
        "        print(f'  ❌ Error calculating metrics: {e}')\n",
        "\n",
        "# Create metrics DataFrame\n",
        "if metrics_results:\n",
        "    metrics_df = pd.DataFrame(metrics_results)\n",
        "    \n",
        "    print('\\n' + '=' * 80)\n",
        "    print('📊 METRICS SUMMARY')\n",
        "    print('=' * 80)\n",
        "    print(metrics_df.to_string(index=False))\n",
        "    print('=' * 80)\n",
        "else:\n",
        "    print('\\n⚠️  No metrics calculated')\n",
        "    metrics_df = pd.DataFrame()"
    ]
})

# Metrics Visualization
notebook["cells"].append({
    "cell_type": "code",
    "id": "viz-metrics",
    "metadata": {},
    "execution_count": None,
    "outputs": [],
    "source": [
        "# Visualize metrics comparison\n",
        "if not metrics_df.empty:\n",
        "    fig, axes = plt.subplots(1, 3, figsize=(18, 6))\n",
        "    fig.suptitle('Clustering Quality Metrics Comparison', fontsize=16, fontweight='bold')\n",
        "    \n",
        "    methods = metrics_df['Method'].values\n",
        "    x_pos = np.arange(len(methods))\n",
        "    \n",
        "    # Plot 1: Silhouette Score (higher is better)\n",
        "    ax = axes[0]\n",
        "    bars = ax.bar(x_pos, metrics_df['Silhouette'], color='skyblue', edgecolor='black')\n",
        "    best_idx = metrics_df['Silhouette'].idxmax()\n",
        "    bars[best_idx].set_color('gold')\n",
        "    bars[best_idx].set_edgecolor('red')\n",
        "    bars[best_idx].set_linewidth(2)\n",
        "    ax.set_xticks(x_pos)\n",
        "    ax.set_xticklabels(methods, rotation=45, ha='right')\n",
        "    ax.set_ylabel('Silhouette Score', fontweight='bold')\n",
        "    ax.set_title('Silhouette Score (↑ higher is better)')\n",
        "    ax.grid(axis='y', alpha=0.3)\n",
        "    \n",
        "    for i, (bar, val) in enumerate(zip(bars, metrics_df['Silhouette'])):\n",
        "        ax.text(i, val + 0.01, f'{val:.4f}', ha='center', va='bottom', fontsize=10)\n",
        "    \n",
        "    # Plot 2: Davies-Bouldin Index (lower is better)\n",
        "    ax = axes[1]\n",
        "    bars = ax.bar(x_pos, metrics_df['Davies-Bouldin'], color='lightcoral', edgecolor='black')\n",
        "    best_idx = metrics_df['Davies-Bouldin'].idxmin()\n",
        "    bars[best_idx].set_color('gold')\n",
        "    bars[best_idx].set_edgecolor('red')\n",
        "    bars[best_idx].set_linewidth(2)\n",
        "    ax.set_xticks(x_pos)\n",
        "    ax.set_xticklabels(methods, rotation=45, ha='right')\n",
        "    ax.set_ylabel('Davies-Bouldin Index', fontweight='bold')\n",
        "    ax.set_title('Davies-Bouldin Index (↓ lower is better)')\n",
        "    ax.grid(axis='y', alpha=0.3)\n",
        "    \n",
        "    for i, (bar, val) in enumerate(zip(bars, metrics_df['Davies-Bouldin'])):\n",
        "        ax.text(i, val + 0.02, f'{val:.4f}', ha='center', va='bottom', fontsize=10)\n",
        "    \n",
        "    # Plot 3: Calinski-Harabasz Score (higher is better)\n",
        "    ax = axes[2]\n",
        "    bars = ax.bar(x_pos, metrics_df['Calinski-Harabasz'], color='lightgreen', edgecolor='black')\n",
        "    best_idx = metrics_df['Calinski-Harabasz'].idxmax()\n",
        "    bars[best_idx].set_color('gold')\n",
        "    bars[best_idx].set_edgecolor('red')\n",
        "    bars[best_idx].set_linewidth(2)\n",
        "    ax.set_xticks(x_pos)\n",
        "    ax.set_xticklabels(methods, rotation=45, ha='right')\n",
        "    ax.set_ylabel('Calinski-Harabasz Score', fontweight='bold')\n",
        "    ax.set_title('Calinski-Harabasz Score (↑ higher is better)')\n",
        "    ax.grid(axis='y', alpha=0.3)\n",
        "    \n",
        "    for i, (bar, val) in enumerate(zip(bars, metrics_df['Calinski-Harabasz'])):\n",
        "        ax.text(i, val + 50, f'{val:.0f}', ha='center', va='bottom', fontsize=10)\n",
        "    \n",
        "    plt.tight_layout()\n",
        "    plt.show()\n",
        "    \n",
        "    print('✅ Metrics visualization complete!')\n",
        "else:\n",
        "    print('⚠️  No metrics to visualize')"
    ]
})

# Ranking
notebook["cells"].append({
    "cell_type": "markdown",
    "id": "ranking-title",
    "metadata": {},
    "source": [
        "## 🏆 5. Method Ranking"
    ]
})

notebook["cells"].append({
    "cell_type": "code",
    "id": "ranking",
    "metadata": {},
    "execution_count": None,
    "outputs": [],
    "source": [
        "# Rank methods by each metric\n",
        "if not metrics_df.empty:\n",
        "    print('=' * 80)\n",
        "    print('🏆 METHOD RANKING BY METRICS')\n",
        "    print('=' * 80)\n",
        "    \n",
        "    # Silhouette (higher is better)\n",
        "    print('\\n1. Silhouette Score (higher is better):')\n",
        "    silhouette_ranking = metrics_df.sort_values('Silhouette', ascending=False)\n",
        "    for idx, row in silhouette_ranking.iterrows():\n",
        "        print(f'   {idx+1}. {row[\"Method\"]:<15s}: {row[\"Silhouette\"]:.4f}')\n",
        "    \n",
        "    # Davies-Bouldin (lower is better)\n",
        "    print('\\n2. Davies-Bouldin Index (lower is better):')\n",
        "    db_ranking = metrics_df.sort_values('Davies-Bouldin', ascending=True)\n",
        "    for idx, row in db_ranking.iterrows():\n",
        "        print(f'   {idx+1}. {row[\"Method\"]:<15s}: {row[\"Davies-Bouldin\"]:.4f}')\n",
        "    \n",
        "    # Calinski-Harabasz (higher is better)\n",
        "    print('\\n3. Calinski-Harabasz Score (higher is better):')\n",
        "    ch_ranking = metrics_df.sort_values('Calinski-Harabasz', ascending=False)\n",
        "    for idx, row in ch_ranking.iterrows():\n",
        "        print(f'   {idx+1}. {row[\"Method\"]:<15s}: {row[\"Calinski-Harabasz\"]:.2f}')\n",
        "    \n",
        "    # Overall ranking (rank-based scoring)\n",
        "    print('\\n' + '=' * 80)\n",
        "    print('🎯 OVERALL RANKING (Rank-based Scoring)')\n",
        "    print('=' * 80)\n",
        "    \n",
        "    scores = {method: 0 for method in metrics_df['Method']}\n",
        "    n_methods = len(metrics_df)\n",
        "    \n",
        "    # Silhouette ranking\n",
        "    for rank, row in enumerate(silhouette_ranking.iterrows(), 1):\n",
        "        scores[row[1]['Method']] += (n_methods - rank + 1)\n",
        "    \n",
        "    # Davies-Bouldin ranking\n",
        "    for rank, row in enumerate(db_ranking.iterrows(), 1):\n",
        "        scores[row[1]['Method']] += (n_methods - rank + 1)\n",
        "    \n",
        "    # Calinski-Harabasz ranking\n",
        "    for rank, row in enumerate(ch_ranking.iterrows(), 1):\n",
        "        scores[row[1]['Method']] += (n_methods - rank + 1)\n",
        "    \n",
        "    # Sort by total score\n",
        "    sorted_scores = sorted(scores.items(), key=lambda x: x[1], reverse=True)\n",
        "    \n",
        "    print(f'\\n🥇 WINNER: {sorted_scores[0][0]}')\n",
        "    print(f'   Total Score: {sorted_scores[0][1]}/{n_methods*3}\\n')\n",
        "    \n",
        "    for rank, (method, score) in enumerate(sorted_scores, 1):\n",
        "        medal = '🥇' if rank == 1 else '🥈' if rank == 2 else '🥉' if rank == 3 else '  '\n",
        "        print(f'{medal} {rank}. {method:<15s}: {score}/{n_methods*3} points')\n",
        "    \n",
        "    print('=' * 80)\n",
        "else:\n",
        "    print('⚠️  No metrics available for ranking')"
    ]
})

# Save updated notebook
with open('carbon24-clustering-comparison-evaluation.ipynb', 'w', encoding='utf-8') as f:
    json.dump(notebook, f, indent=1, ensure_ascii=False)

print('✅ Part 2 added: Metrics calculation and ranking')
print('   Total cells:', len(notebook['cells']))
